# rustfmt configuration
# https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 100
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
use_field_init_shorthand = true
use_try_shorthand = true
newline_style = "Unix"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = false
